### ISSUE TITLE
 Rename orca injectables and tables for control totals (block_hooks)

### ISSUE THREAD

**Issue by PyMap** [urbansim/urbansim_hooks#5]
Change the order on 'if/elif/else' structure on transition models (hh & jobs) to give priority to the 'control_totals' imported from UI:

```@orca.step('households_transition')
def households_transition(households, persons, year):
    if 'household_growth_rate' in orca.list_injectables():
        households_transition_basic(households, persons)
    elif 'annual_household_control_totals' in orca.list_tables():
        household_controls = orca.get_table('annual_household_control_totals')
        if 'county_id' in household_controls.columns:
            print("need to implement subregional ct")
        full_transition(households, household_controls, year, 'block_id',
                        linked_tables={
                            'persons': (persons, 'household_id')})
    else:
        households_transition_basic(households, persons)```

A possible solution would be changing the injectable name on scenario inputs and use it inside the function.

**Comment by PyMap** [comment]
@msoltadeo thanks for your observations! as you said, it is clear how the control total are overwritten. I won't change anything for the moment (just working locally) but we are thinking about the possibility of spliting orca tables and injectables to quickly recognize the ones that are coming from the UI. And, instead of overwrite give them the priority and if they don't exist use the local inputs. For the moment, this is just a workaround.

**Comment by msoltadeo** [comment]
Sounds good.

**Comment by PyMap** [comment]
Make UI inputs take precedence over data_model.h5 file added to hooks documentation.
